name: Release

on:
  push:

permissions:
  contents: write

jobs:
  release-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: optimize Wasm
        uses: NiklasEi/wasm-opt-action@v2
        with:
          file: target/wasm32-unknown-unknown/release/conveyor.wasm

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/wasm32-unknown-unknown/release/conveyor.wasm
          asset_name: conveyor.wasm
          tag: 0.1.0
          overwrite: true
