name: Release

on:
  push:

env:
  itch_target: the_trav/conveyor

jobs:
  release-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Prepare package
        run: |
          cargo install -f wasm-bindgen-cli
          wasm-bindgen --no-typescript --out-name conveyor --out-dir wasm --target web target/wasm32-unknown-unknown/release/conveyor.wasm
          cp -r assets wasm/

      - name: Package as a zip
        working-directory: ./wasm
        run: |
          zip --recurse-paths ../conveyor.zip .

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          ./butler push \
              --fix-permissions \
              --userversion="${{ steps.get_version.outputs.tag }}" \
              conveyor.zip \
              ${{ env.itch_target }}:wasm
          